Improve write performance
timescale/prometheus-postgresql-adapter pull request #36
Opened 2018-08-24 15:41 UTC by niksajakovljevic

For normalized table setup we skip using DB triggers (existing triggers in pg_prometheus appear to be slow), but write first into short lived temporary table and then inserting data into labels and values tables from there. Temporary table data is cleaned on each commit. Refactoring db tests to use the actual client creation logic.

2018-08-27 15:08 UTC, RobAtticus requested changes

2018-08-27 15:08 UTC, RobAtticus commented on postgresql/client.go
> +	flag.StringVar(&cfg.copyTable, "pg.copy-table", "", "The PostgreSQL table")
These flags have identical descriptions so its a bit confusing what they do

2018-08-27 15:08 UTC, RobAtticus commented on postgresql/client.go
> +const sqlCreateTmpTable = "CREATE TEMPORARY TABLE IF NOT EXISTS %s_tmp(sample prom_sample) ON COMMIT DELETE ROWS;"
change to a const grouping?:
```
const (
  sqlCreateTmpTable = ...
  ...
)
```

2018-08-27 15:08 UTC, RobAtticus commented on postgresql/client.go
> +	createTmpTableStmt, err = db.Prepare(fmt.Sprintf(sqlCreateTmpTable, cfg.table))
`err` not checked or used here?

2018-08-28 13:37 UTC, RobAtticus approved these changes

2018-08-29 09:58 UTC, davidkohn88 approved these changes
SQL looks fine.

2018-08-29 13:04 UTC, merged