Fix SQL injection
timescale/prometheus-postgresql-adapter pull request #53
Opened 2018-11-16 13:46 UTC by lnovy

This adapter was vulnerable to a SQL injection.

I have run some tests, but nothing too robust.
Also I have never done golang before...

2018-11-29 18:41 UTC, svenklemm requested changes

2018-11-29 18:41 UTC, svenklemm commented on postgresql/client.go
> +	return strings.Replace(strings.Replace(str, `\`, `\\`, -1), `'`, `\'`, -1)
The correct escaping for `'` is `''`. Then you don't need the escape string syntax and can drop the special handling for backslash aswell.

2018-12-04 13:51 UTC, niksajakovljevic reviewed
Hi @lnovy ,

thanks for submitting the PR. I've left some comments. 
Since the adapter is not intended to be used by untrusted users I am not really keen to merge this PR without more testing as it can introduce breaking changes. Can you maybe add some tests?

Would be great to understand your use-case and the need of preventing sql injection.

Thanks,
Niksa

2018-12-04 13:51 UTC, niksajakovljevic commented on postgresql/client.go
> +	return strings.Replace(strings.Replace(str, `\`, `\\`, -1), `'`, `\'`, -1)
I'd rather go for using https://golang.org/pkg/strings/#Replacer, it will be more efficient and nicer to read.

2018-12-04 13:51 UTC, niksajakovljevic commented on postgresql/client.go
> +	"github.com/lib/pq"
I think we only need to initialize the driver, so we should use blank identifier when importing.

2019-01-08 09:12 UTC, niksajakovljevic commented
@lnovy I am closing this since it's been addressed with https://github.com/timescale/prometheus-postgresql-adapter/pull/55

2019-01-08 09:12 UTC, closed without merging