Add reccuring Postgres connection check for advisory lock
timescale/prometheus-postgresql-adapter pull request #91
Opened 2019-09-10 11:53 UTC by antekresic

In a disaster or failover scenario, advisory lock that was previously
acquired would be lost by the leader instance. In this case, we need to
double check that the connection is down and release the
application-side lock to avoid having a state with multiple leaders.

2019-09-12 12:20 UTC, feikesteenbergen approved these changes
LGTM, although instead of specific checkConnection one, I would immediately check the lock at line 98, instead of `checkConnection`, just call `pg_try_advisory_lock` then and there, you could then remove the whole of line 117-128.

2019-09-13 13:05 UTC, niksajakovljevic commented on pkg/util/lock.go
> +			result, _ := l.TryLock()
I think if a connection pooler (eg. pg-bouncer) is sitting between an adapter and PostgreSQL, we might fail to detect that we actually lost the lock (the connection might still show as valid to the adapter). I'd recommend that after we validate the connection we also try getting the lock from the db.

2019-09-13 13:05 UTC, niksajakovljevic commented on cmd/prometheus-postgresql-adapter/main.go
> +	flag.DurationVar(&cfg.lockTimeout, "pg-advisory-lock-timeout", 3*time.Second, "PG advisory lock connection timeout duration. Adapter will resign in case of a lost connection since the lock will be l
Nit: I'd recommend the following argument description: `An interval used by adapter leader to make sure we still hold the lock`

2019-09-13 13:26 UTC, niksajakovljevic requested changes
Overall looks good. My major concern is properly handling a use-case when there is a connection pooler in between and some code structure.

2019-09-13 13:26 UTC, niksajakovljevic commented on cmd/prometheus-postgresql-adapter/main.go
> +	flag.DurationVar(&cfg.lockTimeout, "pg-advisory-lock-timeout", 3*time.Second, "PG advisory lock connection timeout duration. Adapter will resign in case of a lost connection since the lock will be l
Look at my comment about using existing `ScheduledElector` and not introducing new Timer.

2019-09-13 13:26 UTC, niksajakovljevic commented on pkg/util/lock.go
> +		l.lockTimer = time.AfterFunc(l.lockTimeout, func() {
I'd recommend not creating another timer, but instead relying on existing `ScheduledElector`. `ScheduledElector` is responsible for running leader check on certain interval . I guess we would just need to change `IsLeader` implementation of PG advisory lock to actually validate the connection and try re-obtaining the lock. In this case election interval would need to be configurable and default to something more reasonable. (eg. 5 seconds).

2019-09-16 13:23 UTC, niksajakovljevic approved these changes
Looks good!

2019-09-16 15:49 UTC, RobAtticus approved these changes

2019-09-16 15:49 UTC, RobAtticus commented on cmd/prometheus-postgresql-adapter/main.go
> +		os.Exit(1)
perhaps in a follow up PR: maybe change this function to return an error, and then have the caller handle the error with `os.Exit(1)`

2019-09-18 14:19 UTC, merged